name: '[Main] build and deploy'

on: push

jobs:
  build_export:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.12.0
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('**/package-lock.json') }}
    - run: npm install
    - run: npm run build
    - name: upload exported build
      uses: actions/upload-artifact@v1
      with:
        name: out
        path: build

  deploy:
    if: github.ref == 'refs/heads/master'
    needs: build_export
    runs-on: ubuntu-latest

    steps:
    - name: download exported build
      uses: actions/download-artifact@v1
      with:
        name: out
    - run: echo 'react-minesweep.wells.tw' > ./out/CNAME
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
